#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from common import (
    DEFAULT_AUDIO_BITRATE,
    DEFAULT_AUDIO_FADE_MS,
    DEFAULT_VIDEO_CRF,
    DEFAULT_VIDEO_PRESET,
    media_duration,
    parse_timeline_file,
    print_progress,
    render_segments,
    validate_timeline,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Stage 2: apply timeline.json keep ranges to the stage1 VAD output.")
    parser.add_argument("input", type=Path, help="Stage1 VAD output video")
    parser.add_argument("timeline", type=Path, help="timeline.json generated by the LLM")
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Final edited video path. Defaults to <input_stem>_stage2<suffix> next to the stage1 video.",
    )
    parser.add_argument("--audio-fade-ms", type=int, default=DEFAULT_AUDIO_FADE_MS, help="Fade applied per final segment.")
    parser.add_argument("--video-preset", default=DEFAULT_VIDEO_PRESET)
    parser.add_argument("--video-crf", type=int, default=DEFAULT_VIDEO_CRF)
    parser.add_argument("--audio-bitrate", default=DEFAULT_AUDIO_BITRATE)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not args.input.exists():
        raise FileNotFoundError(f"Input not found: {args.input}")
    if not args.timeline.exists():
        raise FileNotFoundError(f"Timeline not found: {args.timeline}")

    output_path = args.output.resolve() if args.output else args.input.resolve().with_name(f"{args.input.stem}_stage2{args.input.suffix}")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    print_progress("Loading timeline...")
    timeline = parse_timeline_file(args.timeline)
    duration_s = media_duration(str(args.input.resolve()))
    keep_segments = validate_timeline(timeline, duration_s=duration_s)

    print_progress(
        f"Applying {len(keep_segments)} keep ranges "
        f"({sum(segment.duration for segment in keep_segments):.2f}s kept from {duration_s:.2f}s source)..."
    )
    render_segments(
        str(args.input.resolve()),
        str(output_path),
        keep_segments,
        render_chunk_segments=120,
        render_chunk_duration_s=300.0,
        audio_fade_ms=args.audio_fade_ms,
        video_preset=args.video_preset,
        video_crf=args.video_crf,
        audio_bitrate=args.audio_bitrate,
    )
    print_progress(f"Final output: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
